URL = jdbc:mysql://114.212.82.150/dbpedia?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true
#URL = jdbc:mysql://114.212.82.150/yago?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true
JDBC_DRIVER = com.mysql.jdbc.Driver
USER_NAME = root
PASSWORD = lzy199661